apiVersion: apps/v1
kind: Deployment
metadata:
  name: kujakuja-api-server
  labels:
    app: kujakuja-api-server
spec:
  selector:
    matchLabels:
      app: kujakuja-api-server
  template:
    metadata:
      labels:
        app: kujakuja-api-server
    spec:
      containers:
        - name: kujakuja-api-server
          image: eu.gcr.io/kujakuja-dev/kujakuja/api-server:0.0.1
          ports:
            - containerPort: 8080
          # The following environment variables will contain the database host,
          # user and password to connect to the PostgreSQL instance.
          env:
            - name: SQL_DATABASE
              value: kujakuja
            # [START cloudsql_secrets]
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            # [END cloudsql_secrets]
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=kujakuja-dev:europe-west1:kujakuja-db=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END volumes]
