steps:

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['/run-tests.sh']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['bash', '-c', '/prepare-db.sh $$CLOUD_SQL_INSTANCE_CONNECTION_NAME $$CLOUD_SQL_PROXY_PORT']
  env:
  - 'CLOUD_SQL_INSTANCE_CONNECTION_NAME=kujakuja-raiseyourvoice-live:europe-central2:kujakuja-live-db'
  - 'CLOUD_SQL_PROXY_PORT=5433'
  - 'SQL_HOST=localhost'
  - 'SQL_PORT=5433'
  - 'SQL_USER=postgres'
  - 'SQL_DATABASE=kujakuja'
  - 'SQL_SSL=false'
  - 'IDEAS_LANGUAGE=en'
  secretEnv:
  - 'SQL_PASSWORD'

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'app.yaml.template', 'app.yaml']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['app.yaml']
  env:
  - 'SQL_USER=postgres'
  - 'SQL_DATABASE=kujakuja'
  - 'SQL_SSL=false'
  - 'CLOUD_SQL_INSTANCE_CONNECTION_NAME=kujakuja-raiseyourvoice-live:europe-central2:kujakuja-live-db'
  - 'GCP_LOCATION=europe-central2'
  - 'EMAIL_QUEUE_ID=email'
  - 'SLACK_QUEUE_ID=slack'
  - 'NLP_QUEUE_ID=nlp'
  - 'TAGGING_QUEUE_ID=tagging'
  - 'PUB_SUB_QUEUE_ID=data-aggregation-publish'
  - 'DATA_AGGREGATION_PUB_SUB_TOPIC=projects/kujakuja-prod/topics/data-aggregation'
  - 'SYND_QUEUE_ID=syndication'
  - 'SYND_ENV_TYPE=live'
  - 'SYND_TARGET_ENV=raiseyourvoice'
  - 'SYND_SOURCE_ENV=~'
  - 'CONTACT_FORM_TO_ADDRESS=yellow@kujakuja.com'
  - 'CONTACT_FORM_FROM_ADDRESS=website@kujakuja.com'
  - 'CONTACT_FORM_SUBJECT=New Contact Form Submission'
  - 'DATAFIX_AUDIT_TO_ADDRESS=kujakuja@atomicdata.com;cjoseph@kujakuja.com'
  - 'DATAFIX_AUDIT_FROM_ADDRESS=website@kujakuja.com'
  - 'DATAFIX_AUDIT_SUBJECT=Data Fix Applied'
  - 'IDEAS_LANGUAGE=en'
  - 'FRONTEND_LOGIN_REQUIRED=false'
  - 'SLACK_CHANNEL_ID=C0136AC53PX'
  secretEnv:
  - 'SQL_PASSWORD'
  - 'JWT_SECRET'
  - 'SENDGRID_API_KEY'
  - 'SLACK_TOKEN'

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'cron.yaml.template', 'cron.yaml']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['cron.yaml']
  env:
  - 'TIME=04:00'
  - 'TIMEZONE=UTC'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--promote', '--version=$TAG_NAME', '--project=kujakuja-raiseyourvoice-live']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'cron.yaml', '--project=kujakuja-raiseyourvoice-live']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      SQL_PASSWORD: CiQAnpDxcRDYyixxmWox37MSwS45m4DnO4h2JUiVNebLn7TVCzYSOAD8O7eK40SdnhQTjELSOrneNik+y0+LydGnNMWkaD6p6w39MClHmypE5VXFAA7XwWq8g/Qjf/MJ
      JWT_SECRET: CiQAnpDxcQOwWw3AeCLTLYpLhapnv3+YDI0sunGyAnIMODfDU7MSfQD8O7eKMZO+HYCH3RfTpAtWt+k1unGEbdqnrc/O0y+YABWqaDL7Sgk0A6h0RjG2NTPGppqrwEvlHhFw4dRX5/Y2yLaGMVzhbzh+2OrlsLPPP6uyzNUPq58a/KmpE0stifCS2zLbA652FKWanwAwypu+FYj+8YVtSnKTsUwS
      SENDGRID_API_KEY: CiQAnpDxccJ530O9CMZgclzjNBOK0UxXSCdM21LtCuqSFDPWJgsSbgD8O7eKeb3mhUez6VjPAu3gKWCM1Zt3HOcCblFyKcMCPELsuKNJKdH0nuHWaa5/O7/1PZ3m8GMm6zbCb8gQAfQim+ltemKEZNTj4OBTfWxGusC4rUMClwfINZt04U0yg/2Bxqc45J1fQbC7I8lv
      SLACK_TOKEN: CiQAnpDxceUV3FaVQ5DkRxmmzo/g8wl0s3aQdX+UQRWo8/Ms678SYAD8O7eK8U+bfIUjuukpWBaudU/yBzXiv/sHMWBB40ZAxpO47QdUK0PYmKIG6lz3qqg/Y3MQfaT4V3QoXPZr+fT75NbICQTUN1JOKLFw95dYpxDhwzr+/P7ZXiwUI9riqw==

timeout: '1800s'
