steps:

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['/run-tests.sh']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['bash', '-c', '/prepare-db.sh $$CLOUD_SQL_INSTANCE_CONNECTION_NAME $$CLOUD_SQL_PROXY_PORT']
  env:
  - 'CLOUD_SQL_INSTANCE_CONNECTION_NAME=kujakuja-ofda-dev:southamerica-east1:kujakuja-dev-db'
  - 'CLOUD_SQL_PROXY_PORT=5433'
  - 'SQL_HOST=localhost'
  - 'SQL_PORT=5433'
  - 'SQL_USER=postgres'
  - 'SQL_DATABASE=kujakuja'
  - 'SQL_SSL=false'
  - 'IDEAS_LANGUAGE=es'
  secretEnv:
  - 'SQL_PASSWORD'

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'app.yaml.template', 'app.yaml']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['app.yaml']
  env:
  - 'SQL_USER=postgres'
  - 'SQL_DATABASE=kujakuja'
  - 'SQL_SSL=false'
  - 'CLOUD_SQL_INSTANCE_CONNECTION_NAME=kujakuja-ofda-dev:southamerica-east1:kujakuja-dev-db'
  - 'GCP_LOCATION=southamerica-east1'
  - 'EMAIL_QUEUE_ID=email'
  - 'SLACK_QUEUE_ID=slack'
  - 'NLP_QUEUE_ID=nlp'
  - 'TAGGING_QUEUE_ID=tagging'
  - 'PUB_SUB_QUEUE_ID=data-aggregation-publish'
  - 'DATA_AGGREGATION_PUB_SUB_TOPIC=projects/kujakuja-dev/topics/data-aggregation'
  - 'SYND_QUEUE_ID=syndication'
  - 'SYND_ENV_TYPE=dev'
  - 'SYND_TARGET_ENV=ofda'
  - 'SYND_SOURCE_ENV=crc,adra,nrc,world-vision,aah,drc'
  - 'CONTACT_FORM_TO_ADDRESS=yellow@kujakuja.com'
  - 'CONTACT_FORM_FROM_ADDRESS=website@kujakuja.com'
  - 'CONTACT_FORM_SUBJECT=New Contact Form Submission'
  - 'DATAFIX_AUDIT_TO_ADDRESS=kujakuja@atomicdata.com;jcollery@kujakuja.com;cjoseph@kujakuja.com'
  - 'DATAFIX_AUDIT_FROM_ADDRESS=website@kujakuja.com'
  - 'DATAFIX_AUDIT_SUBJECT=Data Fix Applied'
  - 'IDEAS_LANGUAGE=es'
  - 'FRONTEND_LOGIN_REQUIRED=true'
  - 'SLACK_CHANNEL_ID=C0136AC53PX'
  - 'SLACK_ACTION_AMPLIFIER_CHANNEL_ID=CQ7DPBTCG'
  secretEnv:
  - 'SQL_PASSWORD'
  - 'JWT_SECRET'
  - 'SENDGRID_API_KEY'
  - 'SLACK_TOKEN'

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'cron.yaml.template', 'cron.yaml']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['cron.yaml']
  env:
  - 'TIME=06:00'
  - 'TIMEZONE=America/Bogota'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--promote', '--version=$TAG_NAME', '--project=kujakuja-ofda-dev']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'cron.yaml', '--project=kujakuja-ofda-dev']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      SQL_PASSWORD: CiQAnpDxcT38qoGECYu/wt+E+kp210iSuGUKL/YaZr4fClompIESOQD8O7eKWHzDz5PTO7uskqdJi3T1YDZnuEg3gCd3bb2lwltm/kbUL5ZpsQeXMhL4AlT0/Hm0bkgmzQ==
      JWT_SECRET: CiQAnpDxcSUpTG/EpFWFv7ybR15tl+aRQD40v/ds4tNAImA3KigSfwD8O7eK4NJC9j8tH7oX9fjiQr/lY8RJxZaTLZ4Ht2u7CGaPrcY3t23JgYyefowVNGik5rqL25YLzPfUXK9EUrdW7TXW+2g/d23qI0TvdFuOR5opwifA+r7LeVE3X+qCSnI71Qn2WNdxCqp94fQm2vgW3L252W6AI74GGHqbsKc=
      SENDGRID_API_KEY: CiQAnpDxccJ530O9CMZgclzjNBOK0UxXSCdM21LtCuqSFDPWJgsSbgD8O7eKeb3mhUez6VjPAu3gKWCM1Zt3HOcCblFyKcMCPELsuKNJKdH0nuHWaa5/O7/1PZ3m8GMm6zbCb8gQAfQim+ltemKEZNTj4OBTfWxGusC4rUMClwfINZt04U0yg/2Bxqc45J1fQbC7I8lv
      SLACK_TOKEN: CiQAnpDxceUV3FaVQ5DkRxmmzo/g8wl0s3aQdX+UQRWo8/Ms678SYAD8O7eK8U+bfIUjuukpWBaudU/yBzXiv/sHMWBB40ZAxpO47QdUK0PYmKIG6lz3qqg/Y3MQfaT4V3QoXPZr+fT75NbICQTUN1JOKLFw95dYpxDhwzr+/P7ZXiwUI9riqw==

timeout: '1800s'
